version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: invoice-backend-mysql
    container_name: invoice_backend_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: invoice_backend_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
